branches:
  only:
  - master

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g npm@3
  - npm install
  - npm run build:test

build: off
version: '{build}'
shallow_clone: true
clone_depth: 1

test_script:
  - node --version
  - npm --version
  - npm test:es5
